# More info: https://docs.roadrunner.dev/docs/general/config

version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: FluffyDiscord\RoadRunnerBundle\Runtime\Runtime
http:
  address: 0.0.0.0:8080
  max_request_size: 1024
  access_logs: false
  middleware: [ "gzip", "sendfile", "static" ]
  static:
    dir: "public"
    forbid: [ ".php" ]
    calculate_etag: false
    weak: false
  pool:
    debug: false
    num_workers: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 75s
      idle_ttl: 10s
      max_worker_memory: 256
      exec_ttl: 60s
logs:
  mode: production
  level: error
  output: [ stdout ]
rpc:
  listen: tcp://127.0.0.1:6001
